In [1]:
from parameters import *
from functions import *
from PDE_solutions import *
walks = 500
N = 200

In [2]:
X0

[-1.5, 1.0]

# MLMV



# Check if there is some POSITIVE correlation (heuristic)

In [3]:
L = 2
N = 200
X0 = np.array([[-1.1,1],
   [-1.3,1],
   [-1.5,1]])
Walks = [2000,1000,200]
Functions = MultilevelFunctionForLDifferentPositions
E, VAR, Var, mean, VarFromTheLwalk = MultiLevelMonteCarlo(L,X0,Walks, Functions, N)

Calculating level 2
Calculating level 1
Calculating level 0
The estimated probability at [[-1.1  1. ]
 [-1.3  1. ]
 [-1.5  1. ]] is: 0.688 (using MC)
with the variance :  0.0017414150479844602
Whithout the variance reduction  0.002297037637816964


In [4]:
E, VAR, Var, mean, VarFromTheLwalk

(array([ 0.724, -0.021, -0.015]),
 array([0.447, 0.242, 0.255]),
 0.0017414150479844602,
 0.688,
 0.002297037637816964)

In [5]:
L = 5
X0 = np.array([-1.5,1])

N0 = 400
NL = 500
N = createVectorN(N0,NL,L)
#Walks = [5000, 4000, 3000, 2000, 1000, 200]
#Walks = [N[len(N)-i-1] for i in range(len(N))]
Walks = [ round(1000 * 2 **-i) for i in range(L+1)]
#Walks = [500,400]
Function = MultilevelFunctionForLDifferentTimesSteps
E, VAR, Var, mean, VarFromTheLwalk = MultiLevelMonteCarlo(L,X0,Walks, Function, N)

Calculating level 5
Calculating level 4
Calculating level 3
Calculating level 2
Calculating level 1
Calculating level 0
The estimated probability at [-1.5  1. ] is: 0.774516129032258 (using MC)
with the variance :  0.010365910431051228
Whithout the variance reduction  0.014348474934663525


In [6]:
L = 6
X0 = np.array([-1.5,1])

N0 = 1000
NL = 2000
N = np.linspace(N0,NL,num=L+1,dtype=int)
#Walks = [5000, 4000, 3000, 2000, 1000, 200]
Walks = [ round(100 + 2 **-i) for i in range(L+1)]
#Walks = [500,400]
Function = MultilevelFunctionForLDifferentTimesSteps
E, VAR, Var, mean, VarFromTheLwalk = MultiLevelMonteCarlo(L,X0,Walks, Function, N)

Calculating level 6
Calculating level 5
Calculating level 4
Calculating level 3
Calculating level 2
Calculating level 1
Calculating level 0
The estimated probability at [-1.5  1. ] is: 0.7722772277227723 (using MC)
with the variance :  0.014374405100871948
Whithout the variance reduction  0.004163331998932266


In [7]:
VAR/np.array(Walks[:-1])

array([0.004, 0.002, 0.002, 0.001, 0.001, 0.001, 0.002])

In [8]:
def createInvertedVectorN(N0, NL, L):
    """
    N0 : number of iteration for the level 0
    NL : number of iteration for the level L, level of interest
    L : number of Levels
    output : N vector of size L+1 with the Nl invertly distributed
    """
    #dtl = dt0 * M**(1-l) and N = T / dt
    #N0/Nl = M**(1-l)
    M = (N0/NL) ** (1/(1-L))
    #Nl = N0/(M**(1-l))
    return np.array([ round(N0 / (M**(1-l))) for l in range(L+1)],dtype=int)  

In [9]:
createInvertedVectorN(N0,NL,L)

array([ 871, 1000, 1149, 1320, 1516, 1741, 2000])

In [10]:
createVectorN(N0,NL,L)

array([1000, 1122, 1260, 1414, 1587, 1782, 2000])

In [11]:
#creates different walks with different

In [12]:
t0 = 0.1
tf = 0.01
L = 3
M = int( (t0/tf)**(1/L) )
M

2