# MLMC Multi-Level Monte Carlo

In [1]:
import sys
sys.path.append('..')
from parameters import *
from functions import *

X0 = [-1.5, 1]
PDEProb = 0.7173050315908374

## A. With different starting positions

In [2]:
#defines variables for the MLMC with different starting positions
L = 5
N = 200

X0 = np.c_[np.linspace(-1, -1.5,L+1), np.linspace(0,1,L+1)] #starting positions, on a line from the point to the well
Walks = np.linspace(10000,100, L+1, dtype=int).tolist()#linear repartition of the number of walks

In [3]:
X0, Walks

(array([[-1. ,  0. ],
        [-1.1,  0.2],
        [-1.2,  0.4],
        [-1.3,  0.6],
        [-1.4,  0.8],
        [-1.5,  1. ]]), [10000, 8020, 6040, 4060, 2080, 100])

In [4]:
#runs a  basic simulation for comparison
_ = BasicMonteCarlo(X0[L], Walks[L], N)


Number of simulations: 100. Time needed = 0.44 s
Estimated variance: 0.4605661864718383
The estimated probability at [-1.5  1. ] is: 0.7 (using MC)
Confidence interval: [ 0.7 +- 0.09138632344891306 ]	with P = 0.95%


In [5]:
#runs the MLMC
Function = MultilevelFunctionForLDifferentPositions #chooses what function will be used for MLMC
E, VAR, Var, mean, VarFromTheLwalk = MultiLevelMonteCarlo(L, X0, Walks, Function, N, verbose=2) #Performs the MLMC

Calculating level 5
Calculating level 4
Calculating level 3
Calculating level 2
Calculating level 1
Calculating level 0

Number of simulations: 30300. Time needed = 18.70 s
The estimated probability at [[-1.   0. ]
 [-1.1  0.2]
 [-1.2  0.4]
 [-1.3  0.6]
 [-1.4  0.8]
 [-1.5  1. ]] is: 0.6233324163355003 (using MLMC)
With the variance reduction:     0.004249941235909293
Whithout the variance reduction: 0.0045126085985421295


In [6]:
#shows variances and expectations of each level
E, VAR, Var, mean, VarFromTheLwalk

(array([ 1.   , -0.002, -0.018, -0.053, -0.103, -0.2  ]),
 array([0.   , 0.049, 0.135, 0.224, 0.304, 0.402]),
 0.004249941235909293,
 0.6233324163355003,
 0.0045126085985421295)

# B. With different timestep each level

In [7]:
#Defines parameters
L = 5
X0 = np.array([-1.5,1])

N0 = 90
NL = 100
#the size of the interval is created as described in the report
N = createVectorN(N0,NL,L)

#the number of walks created as described in the report
k = 2000
Walks = [round(k*2**-i) for i in range(L+1)]
print(Walks, N)

[2000, 1000, 500, 250, 125, 62] [ 90  92  94  96  98 100]


In [8]:
#runs a basic MC simulation for comparison
_ = BasicMonteCarlo(X0, Walks[L], N[L])


Number of simulations: 62. Time needed = 0.17 s
Estimated variance: 0.4945498837527219
The estimated probability at [-1.5  1. ] is: 0.5967741935483871 (using MC)
Confidence interval: [ 0.5967741935483871 +- 0.12559215419852143 ]	with P = 0.95%


In [9]:
#runs the MLMC
Function = MultilevelFunctionForLDifferentTimesSteps
E, VAR, Var, mean, VarFromTheLwalk = MultiLevelMonteCarlo(L, X0, Walks, Function, N, verbose=2)

Calculating level 5
Calculating level 4
Calculating level 3
Calculating level 2
Calculating level 1
Calculating level 0

Number of simulations: 3937. Time needed = 6.71 s
The estimated probability at [-1.5  1. ] is: 0.6423709677419355 (using MLMC)
With the variance reduction:     0.0036885035221680875
Whithout the variance reduction: 0.007780166376096112


In [10]:
#shows variances and expectations of each level
E, VAR, Var, mean, VarFromTheLwalk

(array([ 0.661,  0.001,  0.   ,  0.004, -0.008, -0.016]),
 array([0.473, 0.123, 0.063, 0.11 , 0.089, 0.127]),
 0.0036885035221680875,
 0.6423709677419355,
 0.007780166376096112)